[package]
name = "toc-maker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1"
cityhasher = "0.1"
num = "0.4.3"
sha1 = "0.10"
